import PropTypes from 'prop-types';

const countryCodes = [
	{ code: '+53', name: 'Cuba' },
	{ code: '+1', name: 'Estados Unidos' },
	{ code: '+7', name: 'Rusia' },
	{ code: '+86', name: 'China' },
	{ code: '+91', name: 'India' },
	{ code: '+55', name: 'Brasil' },
	{ code: '+33', name: 'Francia' },
	{ code: '+49', name: 'Alemania' },
	{ code: '+39', name: 'Italia' },
	{ code: '+44', name: 'Reino Unido' },
	{ code: '+81', name: 'Japón' },
	{ code: '+82', name: 'Corea del Sur' },
	{ code: '+34', name: 'España' },
	{ code: '+52', name: 'México' },
	{ code: '+54', name: 'Argentina' },
	{ code: '+61', name: 'Australia' },
	{ code: '+64', name: 'Nueva Zelanda' },
	{ code: '+52', name: 'México' },
	{ code: '+56', name: 'Chile' },
	{ code: '+57', name: 'Colombia' },
	{ code: '+593', name: 'Ecuador' },
	{ code: '+51', name: 'Perú' },
	{ code: '+507', name: 'Panamá' },
	{ code: '+591', name: 'Bolivia' },
	{ code: '+502', name: 'Guatemala' },
	{ code: '+503', name: 'El Salvador' },
	{ code: '+504', name: 'Honduras' },
	{ code: '+505', name: 'Nicaragua' },
	{ code: '+506', name: 'Costa Rica' },
	{ code: '+507', name: 'Panamá' },
	{ code: '+508', name: 'San Pedro y Miquelón' },
	{ code: '+509', name: 'Haití' },
	{ code: '+51', name: 'Perú' },
	{ code: '+55', name: 'Brasil' },
	{ code: '+57', name: 'Colombia' },
	{ code: '+58', name: 'Venezuela' },
	{ code: '+59', name: 'Cuba' },
	{ code: '+593', name: 'Ecuador' },
	{ code: '+594', name: 'Guayana Francesa' },
	{ code: '+595', name: 'Paraguay' },
	{ code: '+596', name: 'Martinica' },
	{ code: '+597', name: 'Surinam' },
	{ code: '+598', name: 'Uruguay' },
	{ code: '+599', name: 'Antillas Neerlandesas' },
	{ code: '+60', name: 'Malasia' },
	{ code: '+61', name: 'Australia' },
	{ code: '+62', name: 'Indonesia' },
	{ code: '+63', name: 'Filipinas' },
	{ code: '+64', name: 'Nueva Zelanda' },
	{ code: '+65', name: 'Singapur' },
	{ code: '+66', name: 'Tailandia' },
	{ code: '+670', name: 'Timor Oriental' },
	{ code: '+671', name: 'Guam' },
	{ code: '+672', name: 'Islas Heard y McDonald' },
	{ code: '+673', name: 'Brunéi' },
	{ code: '+674', name: 'Nauru' },
	{ code: '+675', name: 'Papúa Nueva Guinea' },
	{ code: '+676', name: 'Tonga' },
	{ code: '+677', name: 'Islas Salomón' },
	{ code: '+678', name: 'Vanuatu' },
	{ code: '+679', name: 'Fiyi' },
	{ code: '+680', name: 'Palaos' },
	{ code: '+681', name: 'Wallis y Futuna' },
	{ code: '+682', name: 'Islas Cook' },
	{ code: '+683', name: 'Niue' },
	{ code: '+685', name: 'Samoa' },
	{ code: '+686', name: 'Kiribati' },
	{ code: '+687', name: 'Nueva Caledonia' },
	{ code: '+688', name: 'Tuvalu' },
	{ code: '+689', name: 'Polinesia Francesa' },
	{ code: '+690', name: 'Tokelau' },
	{ code: '+691', name: 'Micronesia' },
	{ code: '+692', name: 'Islas Marshall' },
	{ code: '+7', name: 'Rusia' },
	{ code: '+8', name: 'China' },
	{ code: '+81', name: 'Japón' },
	{ code: '+82', name: 'Corea del Sur' },
	{ code: '+84', name: 'Vietnam' },
	{ code: '+850', name: 'Corea del Norte' },
	{ code: '+852', name: 'Hong Kong' },
	{ code: '+853', name: 'Macao' },
	{ code: '+855', name: 'Camboya' },
	{ code: '+856', name: 'Laos' },
	{ code: '+86', name: 'China' },
	{ code: '+870', name: 'Inmarsat (Atlántico Este)' },
	{ code: '+871', name: 'Inmarsat (Pacífico)' },
	{ code: '+872', name: 'Inmarsat (Índico)' },
	{ code: '+873', name: 'Inmarsat (Atlántico Oeste)' },
	{ code: '+874', name: 'Iridium' },
	{ code: '+875', name: 'Marítimo Móvil' },
	{ code: '+875', name: 'Marítimo Móvil' },
	{ code: '+876', name: 'Marítimo Móvil' },
	{ code: '+877', name: 'Marítimo Móvil' },
	{ code: '+878', name: 'Universal Personal Telecommunications (UPT)' },
	{ code: '+879', name: 'Universal Personal Telecommunications (UPT)' },
	{ code: '+880', name: 'Bangladés' },
	{ code: '+881', name: 'Global Mobile Satellite System (GMSS)' },
	{ code: '+8810', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8811', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8812', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8813', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8816', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8817', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8818', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8819', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+882', name: 'International Networks' },
	{ code: '+883', name: 'International Networks' },
	{ code: '+886', name: 'Taiwán' },
	{ code: '+888', name: 'Telecomunicaciones para desastres' },
	{ code: '+89', name: 'Telecomunicaciones para desastres' },
	{ code: '+850', name: 'Corea del Norte' },
	{ code: '+852', name: 'Hong Kong' },
	{ code: '+853', name: 'Macao' },
	{ code: '+855', name: 'Camboya' },
	{ code: '+856', name: 'Laos' },
	{ code: '+86', name: 'China' },
	{ code: '+870', name: 'Inmarsat (Atlántico Este)' },
	{ code: '+871', name: 'Inmarsat (Pacífico)' },
	{ code: '+872', name: 'Inmarsat (Índico)' },
	{ code: '+873', name: 'Inmarsat (Atlántico Oeste)' },
	{ code: '+874', name: 'Iridium' },
	{ code: '+875', name: 'Marítimo Móvil' },
	{ code: '+876', name: 'Marítimo Móvil' },
	{ code: '+877', name: 'Marítimo Móvil' },
	{ code: '+878', name: 'Universal Personal Telecommunications (UPT)' },
	{ code: '+879', name: 'Universal Personal Telecommunications (UPT)' },
	{ code: '+880', name: 'Bangladesh' },
	{ code: '+881', name: 'Global Mobile Satellite System (GMSS)' },
	{ code: '+8810', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8811', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8812', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8813', name: 'ICO Global (Mobile Satellite Service)' },
	{ code: '+8816', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8817', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8818', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+8819', name: 'AeroMobile (Mobile Satellite Service)' },
	{ code: '+882', name: 'International Networks' },
	{ code: '+883', name: 'International Networks' },
	{ code: '+886', name: 'Taiwan' },
	{ code: '+888', name: 'Telecommunications for Disaster Relief by OCHA' },
	{ code: '+960', name: 'Maldivas' },
	{ code: '+961', name: 'Líbano' },
	{ code: '+962', name: 'Jordania' },
	{ code: '+963', name: 'Siria' },
	{ code: '+964', name: 'Irak' },
	{ code: '+965', name: 'Kuwait' },
	{ code: '+966', name: 'Arabia Saudita' },
	{ code: '+967', name: 'Yemen' },
	{ code: '+968', name: 'Omán' },
	{ code: '+970', name: 'Palestina' },
	{ code: '+971', name: 'Emiratos Árabes Unidos' },
	{ code: '+972', name: 'Israel' },
	{ code: '+973', name: 'Baréin' },
	{ code: '+974', name: 'Catar' },
	{ code: '+975', name: 'Bután' },
	{ code: '+976', name: 'Mongolia' },
	{ code: '+977', name: 'Nepal' },
	{ code: '+98', name: 'Irán' },
	{ code: '+992', name: 'Tayikistán' },
	{ code: '+993', name: 'Turkmenistán' },
	{ code: '+994', name: 'Azerbaiyán' },
	{ code: '+995', name: 'Georgia' },
	{ code: '+996', name: 'Kirguistán' },
	{ code: '+998', name: 'Uzbekistán' },
	{ code: '+1242', name: 'Bahamas' },
	{ code: '+1246', name: 'Barbados' },
	{ code: '+1264', name: 'Anguila' },
	{ code: '+1268', name: 'Antigua y Barbuda' },
	{ code: '+1284', name: 'Islas Vírgenes Británicas' },
	{ code: '+1340', name: 'Islas Vírgenes de los Estados Unidos' },
	{ code: '+1345', name: 'Islas Caimán' },
	{ code: '+1441', name: 'Bermudas' },
	{ code: '+1473', name: 'Granada' },
	{ code: '+1649', name: 'Turcas y Caicos' },
	{ code: '+1664', name: 'Montserrat' },
	{ code: '+1670', name: 'Islas Marianas del Norte' },
	{ code: '+1671', name: 'Guam' },
	{ code: '+1684', name: 'Samoa Americana' },
	{ code: '+1721', name: 'Sint Maarten' },
	{ code: '+1758', name: 'Santa Lucía' },
	{ code: '+1767', name: 'Dominica' },
	{ code: '+1784', name: 'San Vicente y las Granadinas' },
	{ code: '+1787', name: 'Puerto Rico' },
	{ code: '+1809', name: 'República Dominicana' },
	{ code: '+1829', name: 'República Dominicana' },
	{ code: '+1849', name: 'República Dominicana' },
	{ code: '+1868', name: 'Trinidad y Tobago' },
	{ code: '+1869', name: 'San Cristóbal y Nieves' },
	{ code: '+1876', name: 'Jamaica' },
];

const CountryCodeSelect = ({ value, onChange }) => {
	return (
		<select className='form-control me-2' value={value} onChange={onChange}>
			{countryCodes.map((country) => (
				<option key={country.code} value={country.code}>
					{country.name} ({country.code})
				</option>
			))}
		</select>
	);
};

CountryCodeSelect.propTypes = {
	onChange: PropTypes.func.isRequired,
	value: PropTypes.number.isRequired,
};

export default CountryCodeSelect;
